on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Amplify CLI
        run: |
          npm install -g @aws-amplify/cli
          amplify configure --usage-data-off
      - name: Initialize Amplify
        run: |
          amplify init --app https://github.com/${{ github.repository }} --branch ${GITHUB_REF#refs/heads/}
      - name: Build And Deploy
        run: |
          amplify publish

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Remove Amplify App
        run: |
          amplify delete
          amplify env remove dev # optional, remove if not needed
